### ISSUE TITLE
Follow Up to last issue: From the 1st september wan show is not included on website

### ISSUE THREAD

**Issue by DJSMOOTHPANDA** [TheWANDatabase/Website#39]
From  the 1st september to now all of the wan shows are not displayed on the website.

**Comment by AltriusRS** [comment]
Hi there's thanks for opening this issue,


I am currently aware that there has been no shows or topics imported since before September. That is because I am currently managing two very different versions of the project, and they are not compatible with one another.

Sadly this means that whilst I'm working on the rewritten version of the website, and its associated backend services, I am unable to maintain the existing database since all the importing work is done manually.

The new version of the site (once ready) will be a major overhaul that is more than worth the wait, I hope. If I can find the time to do it I will try and get some more recent episodes added to the database for the old site, however I am unable to promise anything with my schedule being as busy as it has been this last two months.

Thanks again,
Thomas

**Comment by DJSMOOTHPANDA** [comment]
thank you for the response
